version: '3.4'

services:
  jupyterlab:
    image: lehela/jupyterlab
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: jupyterlab
    init: true
    environment: 
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./.jupyter:/home/jupyterlab/.jupyter
      - ./notebooks:/home/jupyterlab/notebooks
    ports:
      - 8888:8888
    restart: unless-stopped

